### ISSUE TITLE
setBlending / getBlending

### ISSUE THREAD

**Issue by gbarnovi** [serhiy/libgdx-circular-cooldown#1]
I got an error using this code.
You have to change
**Pixmap**.setBlending(Blending.None);  to ->
**display**.setBlending(Blending.None);
AND
Blending blending = **Pixmap**.getBlending(); to ->
Blending blending = **display**.getBlending();
in those files CooldownTimer / RingCooldownTimer

**Comment by serhiy** [comment]
Hello, thanks for reporting. Indeed there is a problem in this part of the code because in the latest version of libgdx developers have changed the way this property was set. I have updated the project to the latest libgdx version and fixed the issue as you suggested :+1:
